add debug

diff --git a/.github/workflows/delete-maven-packages.yml b/.github/workflows/delete-maven-packages.yml
--- a/.github/workflows/delete-maven-packages.yml
+++ b/.github/workflows/delete-maven-packages.yml
@@ -11,7 +11,14 @@ jobs:
     steps:
       # - name: Install GitHub CLI
       #   uses: cli/cli@v2
-
+      - name: Check if secret is set
+        run: |
+          if [ -z "${{ secrets.DELETE_PACKAGES_PAT }}" ]; then
+            echo "ERROR: DELETE_PACKAGES_PAT is not set!"
+            exit 1
+          else
+            echo "✅ DELETE_PACKAGES_PAT is present"
+          fi
       - name: Authenticate with GitHub CLI
         run: echo "${{ secrets.DELETE_PACKAGES_PAT }}" | gh auth login --with-token
 
